### PR TITLE
fix(core): improve type inference with TypeScript 3.5

### LINKED ISSUE #301: Incorrect type inference with TypeScript 3.5
How to reproduce:
```typescript
import { declareAtom, declareAction } from '@reatom/core'

const action = declareAction()

export const atom = declareAtom({ foo: 'bar' }, on => [
  on(action, () => ({ foo: 'bar' })),
])

export const subAtom = declareAtom(null, on => [
  // atom => Atom<{ foo: string }>
  on(atom, (_, payload) => {
    // payload => Record<TreeId, unknown> <- incorrect type
    return payload
  }),
])
```

### PR DESCRIPTION
**Pull request by stenin-nikita**
fix #301

### CODE REVIEW

File: packages/core/src/declareAtom.ts [hunk 1]
```diff
@@ -22,12 +22,15 @@ export const initAction = initActionCreator()
 type AtomName = TreeId | [string]
 type AtomsMap = { [key: string]: Atom<any> }
 type Reducer<TState, TValue> = (state: TState, value: TValue) => TState
-type DependencyMatcher<TState> = (
-  on: <T>(
+interface DependencyMatcherOn<TState> {
```
Comment (artalar) [inline packages/core/src/declareAtom.ts]: Add a comment to the issue, pls (why we use an interface here)

Comment (stenin-nikita) [reply packages/core/src/declareAtom.ts]: Ok, fixed
