### PR TITLE
fix(react): add batched wrapper for useAction

### LINKED ISSUE #351: Cannot update state inside setInterval
Hello
I have to change the atom value inside setInterval function. 

My first version of the code:
https://gist.github.com/defint/3faffb974ab76b1f7aa8adf0ff2ebadb 
It doesn't work.

My second version of the code with auto-clicking on the button:
https://gist.github.com/defint/fcf383dda69a934bfa411c2b89b72bc4
It works fine.

Can you please describe how to change the state without auto-clicking?

### PR DESCRIPTION
**Pull request by rrrshtt**
fix #351

### CODE REVIEW

File: packages/react/src/index.ts [hunk 1]
```diff
@@ -10,9 +10,16 @@ import {
 } from 'react'
 
 import { Store, Atom, Action } from '@reatom/core'
+import ReactDOM from 'react-dom'
 
 function noop() {}
 
+function batchedFunction(func: Function) {
```
Comment (artalar) [inline packages/react/src/index.ts]: The utility function is unnecessary.

File: packages/react/src/index.ts [hunk 2]
```diff
@@ -141,16 +148,17 @@ export function createActionHook(ctx: Context<Store | null> = context) {
...
     if (!store) throw new Error('[reatom] The provider is not defined')
     if (typeof cb !== 'function') {
       throw new TypeError('[reatom] `useAction` argument must be a function')
     }
 
-    return useCallback((...args) => {
-      const action = cb(...args)
-      if (action) store.dispatch(action)
-    }, deps.concat(store))
+    return batchedFunction(
```
Comment (artalar) [inline packages/react/src/index.ts]: Here u neutralizing the useCallback effect and return a new function every time. It will be better to wrap the dispatch to unstable_batchedUpdates

**Review by artalar — CHANGES_REQUESTED** [review]

**Comment by artalar** [comment]
@rrrshtt thanks a lot for u work on this. I leave some comments, fix it please and add some tests.

**Review by artalar — APPROVED** [review]
