### PR TITLE
fix(core): checks atoms with equal ids

### LINKED ISSUE #140: Multi combine problem. "One of dependencies has the equal id"
```js
import {
  createStore,
  declareAtom,
  declareAction,
  map,
  combine
} from "@reatom/core";

const TAX = 0.13;
const setPrice = declareAction();

const price = declareAtom(0, on => on(setPrice, (state, payload) => payload));

const tax = map(price, price => price * TAX);
const cost = map(combine([price, tax]), ([price, tax]) => price + tax);

const { subscribe, dispatch, getState } = createStore();

subscribe(combine([price, cost, tax]), console.log);
// Error:  [reatom] One of dependencies has the equal id
```

versions: rc13, rc14, rc15 - bug
version: rc12 - ok

codesandbox: https://codesandbox.io/s/broken-night-cl93h

### PR DESCRIPTION
**Pull request by artalar**
fix #140

### CODE REVIEW

File: packages/core/src/__tests__/index.ts [hunk 1]
```diff
@@ -496,5 +496,20 @@ describe('@reatom/core', () => {
       state = root(state, increment())
       expect(getState(state, root)).toEqual([1, 2])
     })
+    test('should checks atoms with equal ids', () => {
+      const update = declareAction()
+
+      const aAtom = declareAtom(0, on =>
+        on(update, (state, payload) => payload),
```
Comment (belozer) [inline packages/core/src/__tests__/index.ts]: not needs

File: packages/core/src/__tests__/index.ts [hunk 2]
```diff
@@ -496,5 +496,20 @@ describe('@reatom/core', () => {
       state = root(state, increment())
       expect(getState(state, root)).toEqual([1, 2])
     })
+    test('should checks atoms with equal ids', () => {
+      const update = declareAction()
```
Comment (belozer) [inline packages/core/src/__tests__/index.ts]: not needs

File: packages/core/src/__tests__/index.ts [hunk 3]
```diff
@@ -496,5 +496,20 @@ describe('@reatom/core', () => {
...
+
+      const aAtom = declareAtom(0, on =>
```
Comment (belozer) [inline packages/core/src/__tests__/index.ts]:
```
const aAtom = declareAtom(0, () => [])
```
